widgets:
    -
        type: toc
        position: left
        index: false
        collapsed: true
        depth: 3
    -
        type: categories
        position: left
    -
        type: tags
        position: left